name: "release"
on:
  push:
    tags:
      - 'v*'
jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v1.0.2
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: "lua functions you don't want to write"
          detailed_description: |
            plenary: full; complete; entire; absolute; unqualified.
            All the lua functions I don't want to write twice.
          template: "./rockspec.template"

